import XCTest
import BigInt
@testable import DigitalPaperKit

/// Validates the Swift crypto port against reference vectors generated by
/// `tools/gen_vectors.py`, which reproduce the dpt-rp1-py reference byte-for-byte.
final class CryptoVectorTests: XCTestCase {

    struct Vectors: Decodable {
        struct HMAC: Decodable { let key, message, digest: String }
        struct PBKDF2: Decodable { let password, salt, derived, authKey, keyWrapKey: String; let iterations, length: Int }
        struct DH: Decodable { let privateKey, publicKey, peerPublicKey, sharedSecret: String }
        struct Wrap: Decodable { let data, authKey, keyWrapKey, iv, wrapped: String }
        let hmac_sha256: HMAC
        let pbkdf2: PBKDF2
        let dh: DH
        let wrap: Wrap
    }

    var vectors: Vectors!

    override func setUpWithError() throws {
        let bundle = Bundle(for: type(of: self))
        let url = try XCTUnwrap(bundle.url(forResource: "vectors", withExtension: "json"),
                               "vectors.json not bundled — check XcodeGen resource handling")
        vectors = try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
    }

    func testHMACSHA256() {
        let v = vectors.hmac_sha256
        let digest = CryptoPrimitives.hmacSHA256(key: hex(v.key), message: hex(v.message))
        XCTAssertEqual(digest.hexString, v.digest)
    }

    func testPBKDF2() {
        let v = vectors.pbkdf2
        let derived = CryptoPrimitives.pbkdf2SHA256(
            password: hex(v.password), salt: hex(v.salt),
            iterations: v.iterations, length: v.length)
        XCTAssertEqual(derived.hexString, v.derived)
        XCTAssertEqual(derived.prefix(32).hexString, v.authKey)
        XCTAssertEqual(derived.suffix(16).hexString, v.keyWrapKey)
    }

    func testDiffieHellmanPublicKey() {
        let v = vectors.dh
        let dh = DiffieHellman(privateKeyBytes: hex(v.privateKey))
        XCTAssertEqual(dh.publicKey().toBytes(256).hexString, v.publicKey)
    }

    func testDiffieHellmanSharedSecret() {
        let v = vectors.dh
        let dh = DiffieHellman(privateKeyBytes: hex(v.privateKey))
        let peer = BigUInt(hex(v.peerPublicKey))
        XCTAssertEqual(dh.sharedSecret(peerPublicKey: peer).toBytes(256).hexString, v.sharedSecret)
    }

    func testWrapMatchesReference() {
        let v = vectors.wrap
        let wrapped = KeyWrap.wrap(hex(v.data), authKey: hex(v.authKey),
                                   keyWrapKey: hex(v.keyWrapKey), iv: hex(v.iv))
        XCTAssertEqual(wrapped.hexString, v.wrapped)
    }

    func testUnwrapRoundTrip() {
        let v = vectors.wrap
        let (data, ok) = KeyWrap.unwrap(hex(v.wrapped), authKey: hex(v.authKey),
                                        keyWrapKey: hex(v.keyWrapKey))
        XCTAssertTrue(ok, "kwa should validate")
        XCTAssertEqual(data.hexString, v.data)
    }

    func testRSASignAndPEMRoundTrip() throws {
        let key = try RSAKey.generate()
        let privPEM = try key.privatePEM()
        XCTAssertTrue(privPEM.contains("BEGIN RSA PRIVATE KEY"))
        let pubPEM = try key.publicPEM()
        XCTAssertTrue(pubPEM.contains("BEGIN PUBLIC KEY"))

        // Re-import the private key and sign with it.
        let reimported = try RSAKey.fromPrivatePEM(privPEM)
        let sig = try reimported.signRSASHA256Base64(Data("nonce-value".utf8))
        XCTAssertFalse(sig.isEmpty)
        XCTAssertNotNil(Data(base64Encoded: sig))
    }

    // MARK: helpers
    private func hex(_ s: String) -> Data { Data(hexString: s) }
}

extension Data {
    var hexString: String { map { String(format: "%02x", $0) }.joined() }
    init(hexString: String) {
        var data = Data(capacity: hexString.count / 2)
        var index = hexString.startIndex
        while index < hexString.endIndex {
            let next = hexString.index(index, offsetBy: 2)
            data.append(UInt8(hexString[index..<next], radix: 16)!)
            index = next
        }
        self = data
    }
}
